
## AttributeError
 'generator' object has no attribute 'next'
```

    在python 3.x中 generator（有yield关键字的函数则会被识别为generator函数）中的next变为__next__了,
    next是python 3.x以前版本中的方法
    修改为下面这样运行正常
    f.__next__()
```

## FileNotFoundError
```
    FileNotFoundError: File b'160801000000_160831235959_181008135719_p1.csv' does not exist
    
    错误原因: 文件如果不在project中,需要加绝对路径
    file_list = os.listdir(r'D:/test/')
    # 用__file__ 更规范,不拉不拉``
    df = pd.read_csv(file_list[0])

```
## TypeError: 'NoneType' object is not subscriptable
```
    df2 = df2.fillna(method='ffill', inplace=True)
    df2['date'] wrong
    
    注意 inplace = True 说明在原dataframe直接改变,不返回类型
    所以df2 变成了NoneType
    再使用 df2['date'] 出错
    
    # .sort 方法不返回,类型为NoneType,用sorted 返回一个类型
    数据预处理时候,对目录下的文件读取路径并排序


```
# SettingWithCopyWarning:
```
    df2.drop(['deviation'], inplace = True, axis=1)
    # 当inplace = True ,直接在原来的dataframe上修改
    # 若该段dataframe被其它引用,会影响到其他的,出警告
    
    # 可以改成不在原来对象上修改
    df2 = df2.drop(['deviation'], axis=1)
    A value is trying to be set on a copy of a slice from a DataFrame
    
    a = [1]
    a.append(3)
    b = a
    
    这是 Python 引用数据类型的问题, 提示,引用对象变化会影响到 共享引用的对象

```

# keyError, 索引问题
```
    df2 = df2[(df2['HHL517CG'] < 10) & (df2['HHL517CG'] > -10)]
    数据筛选之后,索引全部 混乱, 不再是从0开始,不完整
    
    需要重新设定
    df2.shape
    (4977, 4)
    df2 = df2[(df2['HHL517CG'] < 10) & (df2['HHL517CG'] > -10)].reset_index(drop=True)
    df2.reset_index(drop=True) # 将原来的索引列 ('index') 重设
    
    # 或者导出数据时候, index = False, 不输出index
    df2.to_csv(output_path, index=False)

```
# IndexError: list index out of range
```
    # 在处理字符串序,和数字序时候,遇到不同类型文档报错
    path = r'F:/HistoryData/09newprocess/'
    file_list = os.listdir(path)
    print(file_list)
    file_list.sort(key=lambda items: int(re.findall(r'p(\d+).csv', items)[0]))
    
    对目录进行格式化排序时候,如果 有不同类型的文件,则不被正则表达式识别,索引数目不对
```